詳細設計と実装
KeisukeSugita/Seat-monitoring-system pull request #7
Opened 2020-02-20 07:01 UTC by KeisukeSugita

詳細設計レビュー

(cherry picked from commit 7ef29ac6c4edca1b71c09c69cd551cacd96dfd80)

2020-02-20 08:09 UTC, KeisukeSugita commented on src/SeatMonitoringApplicationSln/SeatMonitoringApplication/PeriodicNotifier.cs
> +        public Action<List<Seat>, bool> Destination { get; set; }
コメント付ける

2020-02-20 08:19 UTC, MY00 commented on src/SeatMonitoringApplicationSln/SeatMonitoringApplication/SeatToastNotifier.cs
> +                pastSeats = null;
2回連続してエラーが来たときは、currentSeatsがnullによって、2度目はエラー表示されないようになっている。
これはisSucceededがfalseのときはcurrentSeatsがnullであることを強制している。

前回がエラーであったことを判別しておく必要がある。

2020-02-20 08:19 UTC, MY00 commented on src/SeatMonitoringApplicationSln/SeatMonitoringApplication/SeatToastNotifier.cs
> +                var statusChangeSeats = currentSeats.Where(currentSeat =>
currentSeatsがnullではないことをチェックしておくこと

2020-02-20 08:19 UTC, MY00 commented on src/SeatMonitoringApplicationSln/SeatMonitoringApplication/SeatToastNotifier.cs
> +                        if (pastSeat.name == currentSeat.name)
同じ名前のときは保証していない？
→そうである

2020-02-20 08:19 UTC, MY00 commented on src/SeatMonitoringApplicationSln/SeatMonitoringApplication/SeatToastNotifier.cs
> +                    case "在席":
seat.statusでの判定でいいのでは？

2020-02-20 08:19 UTC, MY00 commented on src/SeatMonitoringApplicationSln/SeatMonitoringApplication/PeriodicNotifier.cs
> +                        Destination(seats, true);
nullチェックが必要

2020-02-20 08:19 UTC, MY00 commented on src/SeatMonitoringApplicationSln/SeatMonitoringApplication/PeriodicNotifier.cs
> +                        Destination(seats, true);
C#6.0以降は
`Destination?.Invoke(seats, true);`
でnullチェックできる（nullなら実行しない）
以下と同等
```
if(Destination !=null )
{
Destination((seats, true);
}
```

2020-02-20 08:21 UTC, MY00 commented on src/SeatMonitoringApplicationSln/SeatMonitoringApplication/ToastNotificationManagerWrapper.cs
> +    /// ToastNotificationManagerクラス、ToastNotifierクラス、ToastNotificationクラスをラップしたクラス
クラス名は「`<see cref="ToastNotificationManager"/>`」のように記述してほしい。

2020-02-21 08:56 UTC, tetsuhigh requested changes

2020-02-21 08:56 UTC, tetsuhigh commented on doc/基本設計/機能仕様書/機能仕様書.md
> +||代替フロー2|座席監視アプリのセットアップを行っていなかった場合 <br> 1. サーバへの接続に失敗したことを示すアイコンを表示する <br> 2. 通知設定がONであっても通知されない|
フロー1が不要

2020-02-21 08:56 UTC, tetsuhigh commented on src/SeatMonitoringApplicationSln/SeatMonitoringApplication/IPeriodicNotifier.cs
> +        Action<List<Seat>, bool> Destination { get; set; }
setが必要？

2020-02-21 08:56 UTC, tetsuhigh commented on src/SeatMonitoringApplicationSln/SeatMonitoringApplication/IPeriodicNotifier.cs
>      public interface IPeriodicNotifier
全体的にIFにコメント

2020-02-21 08:56 UTC, tetsuhigh commented on src/SeatMonitoringApplicationSln/SeatMonitoringApplication/Program.cs
> +                if (Convert.ToBoolean(ConfigurationManager.AppSettings["IsNotify"]))
try~catchするならTryPraseを使う

2020-02-21 08:56 UTC, tetsuhigh commented on src/SeatMonitoringApplicationSln/SeatMonitoringApplication/SeatToastNotifier.cs
> +                statusChangeSeats.ForEach(statusChangeSeat => toastNotificationManager.Show(applicationId, CreateToastNotification(statusChangeSeat, isSucceeded)));
LinqのForEachの使用は非推奨になっている

2020-02-21 08:56 UTC, tetsuhigh commented on src/SeatMonitoringApplicationSln/SeatMonitoringApplication/SeatToastNotifier.cs
> +                Header = new ToastHeader("0001", "座席監視アプリ", ""),
0001はidentifierになっていない

2020-02-21 08:56 UTC, tetsuhigh commented on src/SeatMonitoringApplicationSln/SeatMonitoringApplication/SeatToastNotifier.cs
> +                            Source = $@"{Application.StartupPath}\Icons\{iconName}アイコン.png",
これって複数個所に出てこない？アイコンを取得するためのクラスを作りましょう

2020-02-21 08:56 UTC, tetsuhigh commented on src/SeatMonitoringApplicationSln/SeatMonitoringApplicationTest/SeatToastNotifierTest.cs
> +            Assert.AreEqual(firstTimeSeats, privateObject.GetField("pastSeats"));
これを確認する意図は？

2020-02-21 08:56 UTC, tetsuhigh commented on src/SeatMonitoringApplicationSln/Setup/Setup.cs
> +            System.Runtime.InteropServices.Marshal.FinalReleaseComObject(shortcut);
saveに失敗すると解放されないけど問題ない？

2020-02-21 08:56 UTC, tetsuhigh commented on src/SeatMonitoringApplicationSln/SeatMonitoringApplication/Seat.cs
> +        public readonly Dictionary<SeatStatus, string> SeatStatusLabel = new Dictionary<SeatStatus, string>
コメント

2020-02-21 08:56 UTC, tetsuhigh commented on src/SeatMonitoringApplicationSln/SeatMonitoringApplication/Seat.cs
> +        public readonly Dictionary<SeatStatus, string> SeatStatusLabel = new Dictionary<SeatStatus, string>
dictionaryを公開するのではなくメソッドとして公開してください

2020-02-21 08:56 UTC, tetsuhigh commented on src/SeatMonitoringApplicationSln/SeatMonitoringApplication/Seat.cs
> +        public readonly Dictionary<SeatStatus, string> SeatStatusLabel = new Dictionary<SeatStatus, string>
mainと処理が分散しているので一か所にまとめてください

2020-02-25 05:21 UTC, KeisukeSugita commented on src/SeatMonitoringApplicationSln/SeatMonitoringApplication/IPeriodicNotifier.cs
> +        Action<List<Seat>, bool> Destination { get; set; }
メソッドを代入するために必要だったので残してあります。

2020-02-25 05:23 UTC, KeisukeSugita commented on src/SeatMonitoringApplicationSln/SeatMonitoringApplication/IPeriodicNotifier.cs
>      public interface IPeriodicNotifier
コメント書きました

2020-02-25 05:23 UTC, KeisukeSugita commented on src/SeatMonitoringApplicationSln/SeatMonitoringApplication/PeriodicNotifier.cs
> +        public Action<List<Seat>, bool> Destination { get; set; }
コメント書きました

2020-02-25 05:27 UTC, KeisukeSugita commented on src/SeatMonitoringApplicationSln/SeatMonitoringApplication/SeatToastNotifier.cs
> +                pastSeats = null;
エラーだった状態を保持しておく変数を追加しました。

2020-02-25 05:28 UTC, KeisukeSugita commented on src/SeatMonitoringApplicationSln/SeatMonitoringApplication/SeatToastNotifier.cs
> +                var statusChangeSeats = currentSeats.Where(currentSeat =>
nullチェックを追加しました。

2020-02-25 05:29 UTC, KeisukeSugita commented on src/SeatMonitoringApplicationSln/SeatMonitoringApplication/ToastNotificationManagerWrapper.cs
> +    /// ToastNotificationManagerクラス、ToastNotifierクラス、ToastNotificationクラスをラップしたクラス
コメントにクラス名などが登場する部分を上記指摘のように修正しました。

2020-02-25 05:29 UTC, KeisukeSugita commented on src/SeatMonitoringApplicationSln/SeatMonitoringApplication/PeriodicNotifier.cs
> +                        Destination(seats, true);
nullチェックを追加しました。

2020-02-25 05:30 UTC, KeisukeSugita commented on src/SeatMonitoringApplicationSln/SeatMonitoringApplication/SeatToastNotifier.cs
> +                    case "在席":
判定をSeat.Statusに変更

2020-02-25 05:32 UTC, KeisukeSugita commented on doc/基本設計/機能仕様書/機能仕様書.md
> +||代替フロー2|座席監視アプリのセットアップを行っていなかった場合 <br> 1. サーバへの接続に失敗したことを示すアイコンを表示する <br> 2. 通知設定がONであっても通知されない|
「代替フロー2」の「1. サーバへの接続に失敗したことを示すアイコンを表示する」を削除しました。

2020-02-25 05:33 UTC, KeisukeSugita commented on src/SeatMonitoringApplicationSln/SeatMonitoringApplication/Program.cs
> +                if (Convert.ToBoolean(ConfigurationManager.AppSettings["IsNotify"]))
TryParseで変換を行うよう修正しました。
それに伴い、条件分岐を修正しました。

2020-02-25 05:33 UTC, KeisukeSugita commented on src/SeatMonitoringApplicationSln/SeatMonitoringApplication/SeatToastNotifier.cs
> +                statusChangeSeats.ForEach(statusChangeSeat => toastNotificationManager.Show(applicationId, CreateToastNotification(statusChangeSeat, isSucceeded)));
foreach文に書き換えました。

2020-02-25 05:34 UTC, KeisukeSugita commented on src/SeatMonitoringApplicationSln/SeatMonitoringApplicationTest/SeatToastNotifierTest.cs
> +            Assert.AreEqual(firstTimeSeats, privateObject.GetField("pastSeats"));
privateなメンバにアクセスして値の確認を行っているテストを削除しました。

2020-02-25 05:35 UTC, KeisukeSugita commented on src/SeatMonitoringApplicationSln/Setup/Setup.cs
> +            System.Runtime.InteropServices.Marshal.FinalReleaseComObject(shortcut);
finary文で開放するよう修正しました。

2020-02-25 05:35 UTC, KeisukeSugita commented on src/SeatMonitoringApplicationSln/SeatMonitoringApplication/Seat.cs
> +        public readonly Dictionary<SeatStatus, string> SeatStatusLabel = new Dictionary<SeatStatus, string>
コメント付けました。

2020-02-25 05:36 UTC, KeisukeSugita commented on src/SeatMonitoringApplicationSln/SeatMonitoringApplication/Seat.cs
> +        public readonly Dictionary<SeatStatus, string> SeatStatusLabel = new Dictionary<SeatStatus, string>
Dictionaryを非公開にし、メソッドから値を取得するように修正しました。

2020-02-25 05:37 UTC, KeisukeSugita commented on src/SeatMonitoringApplicationSln/SeatMonitoringApplication/Seat.cs
> +        public readonly Dictionary<SeatStatus, string> SeatStatusLabel = new Dictionary<SeatStatus, string>
MainFormのTooltipTextを廃止し、Seat.SeatStatusで統一しました。

2020-02-25 06:02 UTC, tetsuhigh commented on src/SeatMonitoringApplicationSln/SeatMonitoringApplication/IPeriodicNotifier.cs
> +        Action<List<Seat>, bool> Destination { get; set; }
内部的にsetが実行されるみたいね。addではなく。

http://bbs.wankuma.com/index.cgi?mode=al2&namber=86407&space=15&KLOG=148

2020-02-25 06:31 UTC, tetsuhigh commented on src/SeatMonitoringApplicationSln/SeatMonitoringApplication/IMyHttpClient.cs
> +        /// <param name="requestUri"></param>
メッセージが書いてない

2020-02-25 06:31 UTC, tetsuhigh commented on src/SeatMonitoringApplicationSln/SeatMonitoringApplication/IPeriodicNotifier.cs
> +    /// 指定されたメソッド(Destination)に結果を通知するインターフェース
結果ってなに？

2020-02-25 06:31 UTC, tetsuhigh commented on src/SeatMonitoringApplicationSln/SeatMonitoringApplication/IPeriodicNotifier.cs
> +        /// Startメソッドを終了させるメソッド
これだと裏で同期的に実行されているstart処理を終了するように見える

2020-02-25 06:31 UTC, tetsuhigh commented on src/SeatMonitoringApplicationSln/SeatMonitoringApplication/IPeriodicNotifier.cs
> +        Action<List<Seat>, bool> Destination { get; set; }
コメントがない

2020-02-25 06:31 UTC, tetsuhigh commented on src/SeatMonitoringApplicationSln/SeatMonitoringApplication/ISeatMonitoringApiClient.cs
> +        /// GetSeatsメソッドを呼び出し、結果をアプリが解釈しやすい形に変換するメソッド
GetSeatメソッドとは何？仕様に書いてある？
結果をアプリが解釈しやすい形とは何？

2020-02-25 06:31 UTC, tetsuhigh commented on src/SeatMonitoringApplicationSln/SeatMonitoringApplication/ISeatToastNotifier.cs
> +        /// 1回目の呼び出し時にはトースト通知は行われず、2回も以降の呼び出し時に前回の呼び出し時の引数との差をトースト通知する
サーバーエラーの場合の挙動が書かれていない

2020-02-25 06:31 UTC, tetsuhigh commented on src/SeatMonitoringApplicationSln/SeatMonitoringApplication/IStatusIcon.cs
> +    public interface IStatusIcon
インターフェースいる？

2020-02-25 06:31 UTC, tetsuhigh commented on src/SeatMonitoringApplicationSln/SeatMonitoringApplication/Program.cs
> -                MessageBox.Show(e.Message, "起動エラー", MessageBoxButtons.OK, MessageBoxIcon.Error);
これ消していいの？

2020-02-25 06:31 UTC, tetsuhigh commented on src/SeatMonitoringApplicationSln/SeatMonitoringApplication/Seat.cs
> +        /// <param name="seatStatus"></param>
説明がない

2020-02-25 06:31 UTC, tetsuhigh commented on src/SeatMonitoringApplicationSln/SeatMonitoringApplication/Seat.cs
> +        /// <returns></returns>
戻り値の説明がない

2020-02-25 06:31 UTC, tetsuhigh commented on src/SeatMonitoringApplicationSln/SeatMonitoringApplication/Seat.cs
> +        /// <see cref="SeatStatus"/>から<see cref="SeatStatusLabel"/>に定義されている文字列を取得するメソッド
privateな要素を説明に入れないほうがいい。利用者からは見えないので。

2020-02-25 06:31 UTC, tetsuhigh commented on src/SeatMonitoringApplicationSln/SeatMonitoringApplication/SeatToastNotifier.cs
> +        private bool wasSucceeded = true;
これってどういう英語？

2020-02-25 06:31 UTC, tetsuhigh commented on src/SeatMonitoringApplicationSln/SeatMonitoringApplication/SeatToastNotifier.cs
> +        /// <summary>
IFと同じなら省略していいです。
<see>タグとかでリンクを書くだけで充分。

2020-02-25 06:31 UTC, tetsuhigh commented on src/SeatMonitoringApplicationSln/SeatMonitoringApplication/SeatToastNotifier.cs
> +        private List<Seat> pastSeats = null;
よく最新のといった意味でlatestを使います。

2020-02-25 06:31 UTC, tetsuhigh commented on src/SeatMonitoringApplicationSln/SeatMonitoringApplication/SeatToastNotifier.cs
> +                    statusChangeSeats = currentSeats.Where(currentSeat =>
途中で座席が追加された場合はどうなる？

2020-02-25 06:31 UTC, tetsuhigh commented on src/SeatMonitoringApplicationSln/SeatMonitoringApplication/SeatToastNotifier.cs
> +        private List<Seat> pastSeats = null;
これだと「通知した座席の情報」なのか「座席全部の情報」なのか判断できない

2020-02-25 06:31 UTC, tetsuhigh commented on src/SeatMonitoringApplicationSln/Setup/Setup.cs
> +            System.Runtime.InteropServices.Marshal.FinalReleaseComObject(shortcut);
これってなんで解放が必要かわかった？

2020-02-26 03:58 UTC, KeisukeSugita commented on src/SeatMonitoringApplicationSln/SeatMonitoringApplication/SeatToastNotifier.cs
> +                Header = new ToastHeader("0001", "座席監視アプリ", ""),
Seat Monitoring Application-Toast Notification
にしました。

2020-02-26 03:58 UTC, KeisukeSugita commented on src/SeatMonitoringApplicationSln/SeatMonitoringApplication/SeatToastNotifier.cs
> +                            Source = $@"{Application.StartupPath}\Icons\{iconName}アイコン.png",
StatusIconクラスを作成しました。

2020-02-26 04:05 UTC, KeisukeSugita commented on src/SeatMonitoringApplicationSln/SeatMonitoringApplication/IMyHttpClient.cs
> +        /// <param name="requestUri"></param>
"HTTPリクエストを送信するURI"と記入しました。

2020-02-26 04:06 UTC, KeisukeSugita commented on src/SeatMonitoringApplicationSln/SeatMonitoringApplication/IPeriodicNotifier.cs
> +    /// 指定されたメソッド(Destination)に結果を通知するインターフェース
SeatMonitoringApiClient.GetSeatsの戻り値であることを明記しました。

2020-02-26 04:07 UTC, KeisukeSugita commented on src/SeatMonitoringApplicationSln/SeatMonitoringApplication/IPeriodicNotifier.cs
> +        Action<List<Seat>, bool> Destination { get; set; }
記入しました。

2020-02-26 04:08 UTC, KeisukeSugita commented on src/SeatMonitoringApplicationSln/SeatMonitoringApplication/IPeriodicNotifier.cs
> +        /// Startメソッドを終了させるメソッド
"Startメソッドで非同期に実行されている処理を終了させるメソッド"
と書き換えました。

2020-02-26 04:09 UTC, KeisukeSugita commented on src/SeatMonitoringApplicationSln/SeatMonitoringApplication/ISeatMonitoringApiClient.cs
> +        /// GetSeatsメソッドを呼び出し、結果をアプリが解釈しやすい形に変換するメソッド
"SeatMonitoringAPIのseatsを呼び出し、結果を"Seat"のリストに変換して返すメソッド"
と書き換えました。

2020-02-26 04:09 UTC, KeisukeSugita commented on src/SeatMonitoringApplicationSln/SeatMonitoringApplication/ISeatToastNotifier.cs
> +        /// 1回目の呼び出し時にはトースト通知は行われず、2回も以降の呼び出し時に前回の呼び出し時の引数との差をトースト通知する
追記しました。

2020-02-26 04:11 UTC, KeisukeSugita commented on src/SeatMonitoringApplicationSln/SeatMonitoringApplication/IStatusIcon.cs
> +    public interface IStatusIcon
アイコンへのパスを取得するためだけのクラスで、実装に制限を設ける必要もないと考えたので削除しました。

2020-02-26 04:14 UTC, KeisukeSugita commented on src/SeatMonitoringApplicationSln/SeatMonitoringApplication/Program.cs
> -                MessageBox.Show(e.Message, "起動エラー", MessageBoxButtons.OK, MessageBoxIcon.Error);
try～catchではなくなったため、同様の処理をnullチェックの部分で書いています。

2020-02-26 04:15 UTC, KeisukeSugita commented on src/SeatMonitoringApplicationSln/SeatMonitoringApplication/Seat.cs
> +        /// <see cref="SeatStatus"/>から<see cref="SeatStatusLabel"/>に定義されている文字列を取得するメソッド
SeatStatusLabelが登場しないよう修正しました。

2020-02-26 04:15 UTC, KeisukeSugita commented on src/SeatMonitoringApplicationSln/SeatMonitoringApplication/Seat.cs
> +        /// <param name="seatStatus"></param>
記入しました。

2020-02-26 04:15 UTC, KeisukeSugita commented on src/SeatMonitoringApplicationSln/SeatMonitoringApplication/Seat.cs
> +        /// <returns></returns>
記入しました。

2020-02-26 04:17 UTC, KeisukeSugita commented on src/SeatMonitoringApplicationSln/SeatMonitoringApplication/SeatToastNotifier.cs
> +        private List<Seat> pastSeats = null;
currentをlatestに変更しました。

2020-02-26 04:18 UTC, KeisukeSugita commented on src/SeatMonitoringApplicationSln/SeatMonitoringApplication/SeatToastNotifier.cs
> +        private List<Seat> pastSeats = null;
コメント修正しました。

2020-02-26 04:18 UTC, KeisukeSugita commented on src/SeatMonitoringApplicationSln/SeatMonitoringApplication/SeatToastNotifier.cs
> +        private bool wasSucceeded = true;
isSucceeded,wasSucceeded→pastSucceeded,latestSucceeded
に変更しました。

2020-02-26 04:19 UTC, KeisukeSugita commented on src/SeatMonitoringApplicationSln/SeatMonitoringApplication/SeatToastNotifier.cs
> +        /// <summary>
コメントが同じ部分全てをタグに変更しました。

2020-02-26 04:20 UTC, KeisukeSugita commented on src/SeatMonitoringApplicationSln/SeatMonitoringApplication/SeatToastNotifier.cs
> +                    statusChangeSeats = currentSeats.Where(currentSeat =>
追加された座席の初回通知は飛ばず、2回目以降に状態変化があった場合通知されるようになります。

2020-02-26 05:18 UTC, KeisukeSugita commented on src/SeatMonitoringApplicationSln/Setup/Setup.cs
> +            System.Runtime.InteropServices.Marshal.FinalReleaseComObject(shortcut);
https://docs.microsoft.com/ja-jp/dotnet/api/system.runtime.interopservices.marshal.finalreleasecomobject?view=netframework-4.8
https://docs.microsoft.com/ja-jp/dotnet/standard/native-interop/runtime-callable-wrapper

2020-02-26 07:39 UTC, KeisukeSugita commented on src/SeatMonitoringApplicationSln/SeatMonitoringApplication/SeatToastNotifier.cs
> +        private List<Seat> pastSeats = null;
保持しておくパラメータの名前としてlatestを頭に付け、Notifyの引数はseatsとisSucceededに変更

前回通知時の座席情報はlatestSeatsとlatestIsSucceeded、新しい座席情報はseatsとisSucceeded

2020-02-26 07:40 UTC, merged